name: Publish static site to gh-pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish site
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git switch --orphan gh-pages
          git checkout "$GITHUB_SHA" -- .
          rm -rf .github
          git add --all
          git commit -m "Deploy ${GITHUB_SHA}"
          git push --force origin gh-pages
